"""Custom extension that uploads and exposes files generated by ``/v1/runs``."""

from __future__ import annotations

import logging
import mimetypes
import os
import time
from pathlib import Path
from types import SimpleNamespace
from typing import Any, Dict, List, Optional

from gateway.platforms.custom.file_storage.client import FileStorageServiceClient

from ..base_extension import BaseExtension
from .extractor import extract_artifact_candidates
from .store import RunArtifactStore

logger = logging.getLogger(__name__)

_RUNTIME_ROOT = "/runtime"


class RunArtifactsExtension(BaseExtension):
    """Upload generated files to file-storage and persist run metadata."""

    def __init__(self, auth_checker, client: FileStorageServiceClient) -> None:
        self._client = client
        self._store = RunArtifactStore()

    def register_routes(self, app: Any) -> None:
        return None

    def extend_capabilities(self, caps: Dict[str, Any]) -> None:
        caps["run_artifacts"] = True

    def extend_endpoints(self, endpoints: Dict[str, Any]) -> None:
        return None

    async def close(self) -> None:
        self._store.close()

    async def collect_run_artifacts(
        self,
        run_id: str,
        session_id: str,
        result: Dict[str, Any],
        request_headers: Optional[Dict[str, str]] = None,
    ) -> List[Dict[str, Any]]:
        if not isinstance(result, dict):
            logger.info("Run artifacts: skipped run=%s session=%s (result is not a dict)", run_id, session_id)
            return []
        candidates = extract_artifact_candidates(result)
        if not candidates:
            msg_count = len(result.get("messages") or [])
            logger.info(
                "Run artifacts: no file candidates for run=%s session=%s messages=%d",
                run_id, session_id, msg_count,
            )
            return []

        request = _request_from_headers(request_headers)
        folder_path = _runtime_folder(session_id)
        artifacts: List[Dict[str, Any]] = []
        seen: set[str] = set()
        logger.info(
            "Run artifacts: uploading %d candidate(s) for run=%s session=%s folder=%s",
            len(candidates), run_id, session_id, folder_path,
        )

        for candidate in candidates:
            path = candidate["path"]
            try:
                resolved = str(Path(path).expanduser().resolve())
            except (OSError, RuntimeError, ValueError):
                logger.info(
                    "Run artifacts: skipped invalid candidate path=%r run=%s session=%s",
                    path, run_id, session_id,
                )
                continue
            if resolved in seen:
                logger.info(
                    "Run artifacts: skipped duplicate candidate path=%s run=%s session=%s",
                    resolved, run_id, session_id,
                )
                continue
            if not os.path.isfile(resolved):
                logger.info(
                    "Run artifacts: skipped missing candidate path=%s run=%s session=%s",
                    resolved, run_id, session_id,
                )
                continue
            seen.add(resolved)

            filename = Path(resolved).name
            mime_type = mimetypes.guess_type(resolved)[0] or "application/octet-stream"
            try:
                data = Path(resolved).read_bytes()
            except OSError as exc:
                logger.warning("Run artifact read failed for %s: %s", resolved, exc)
                continue

            try:
                uploaded = await self._client.upload(
                    file_id="",
                    filename=filename,
                    mime_type=mime_type,
                    data=data,
                    request=request,
                    folder_path=folder_path,
                )
            except Exception as exc:
                logger.warning("Run artifact upload failed for %s: %s", resolved, exc)
                continue

            artifact_id = uploaded.public_id
            remote_path = f"/hermes-agent{folder_path}/{filename}"
            meta = self._store.put(
                run_id=run_id,
                session_id=session_id,
                tool_call_id=candidate.get("tool_call_id", ""),
                tool_name=candidate.get("tool_name", ""),
                artifact_id=artifact_id,
                public_id=uploaded.public_id,
                filename=filename,
                mime_type=mime_type,
                size_bytes=len(data),
                remote_url=uploaded.remote_url,
                remote_path=remote_path,
            )
            if meta:
                artifacts.append(self._store.public_metadata(meta))
                logger.info(
                    "Run artifacts: uploaded %s via %s tool_call_id=%s publicId=%s",
                    filename,
                    candidate.get("tool_name", ""),
                    candidate.get("tool_call_id", ""),
                    artifact_id,
                )

        if artifacts:
            logger.debug(
                "Run artifacts: uploaded %d artifact(s) for run=%s session=%s",
                len(artifacts), run_id, session_id,
            )
        else:
            logger.info(
                "Run artifacts: no artifact uploaded for run=%s session=%s candidates=%d",
                run_id, session_id, len(candidates),
            )
        return artifacts

    def list_run_artifacts(self, run_id: str) -> List[Dict[str, Any]]:
        return [
            self._store.public_metadata(item)
            for item in self._store.list_run(run_id)
        ]

    def list_tool_call_artifacts(
        self, tool_call_ids: List[str],
    ) -> List[Dict[str, Any]]:
        return [
            self._store.public_metadata(item)
            for item in self._store.list_tool_call_ids(tool_call_ids)
        ]


def _runtime_folder(session_id: str) -> str:
    day = time.strftime("%Y-%m-%d", time.localtime())
    safe_session_id = _safe_path_segment(session_id)
    return f"{_RUNTIME_ROOT}/{day}/{safe_session_id}"


def _safe_path_segment(value: str) -> str:
    cleaned = "".join(
        ch if ch.isalnum() or ch in {"_", "-"} else "_"
        for ch in str(value or "").strip()
    )
    return cleaned or "session"


def _request_from_headers(headers: Optional[Dict[str, str]]):
    if not headers:
        return None
    return SimpleNamespace(headers=headers)
